### ISSUE TITLE
Default communication device

### ISSUE THREAD

**Issue by oddbear** [KillerBOSS2019/WinTools#1]
Change the default communication device individually from the default device is not supported.
There is a PR _(that I think has a little bug)_ in it on the AudioDeviceCmdlets.

This is set by the `ERole.eCommunications` and `ERole.eMultimedia` roles.

**Comment by DamienStaebler** [comment]
I am moving audio mixer stuff in another plugin. And I've added a feature to change communication input and output. 

https://github.com/KillerBOSS2019/TouchPortal-Windows-MediaMixer
