### ISSUE TITLE
In change audio source device is showing empty 

### ISSUE THREAD

**Issue by SLFaleiro** [KillerBOSS2019/WinTools#11]
In change audio source device is showing empty .

I tried to remove and reinstall the wintools plugin didn't help. 
I also tried 2 versions down also didn't help help

**Comment by DamienStaebler** [comment]
Hi, I've separated the audio part of plugin into another plugin. This new one should fix the issue. 

https://github.com/KillerBOSS2019/TouchPortal-Windows-MediaMixer

**Comment by DamienStaebler** [comment]
If you have any more questions feel free to open another issue in that repository.
