### ISSUE TITLE
State "[Sound] Get Current Input Device" not working

### ISSUE THREAD

**Issue by GeekyAdam** [KillerBOSS2019/WinTools#12]
STR:
1. Install latest WinTools plugin version 241
2. Close and reopen Touch Portal
3. Have two audio input devices.
4. Device 1 is currently default device (confirmed via Windows Sound Control Panel - Recording tab).
5. Create Touch Portal button with event to update button text each cycle, set value to `${value:KillerBOSS.TP.Plugins.Sound.CurrentInputDevice}`.
6. Button updates successfully, but shows device 2.
7. In Windows, change default input audio device successfully to device 2, wait a minute, change back to device 1.
8. Button value never shows device 1 correctly, just keeps showing device 2.

I was building a button to detect current default input device and toggle between device 1 and 2, but I am not able to, as the `${value:KillerBOSS.TP.Plugins.Sound.CurrentInputDevice}` value is not accurate.

**Comment by DamienStaebler** [comment]
Sorry. This plugin no longer supports audio switching. as this feature moved to Win-MediaMixer plugin.
