### ISSUE TITLE
Request: Change Focused Window

### ISSUE THREAD

**Issue by 40wattrange** [KillerBOSS2019/WinTools#8]
Ability to focus on specific window/app.

**Comment by gitagogaming** [comment]
I've updated the most recent version of WinTools to include this.   This feature was mistakenly removed in the past.

This will give you the option to focus an application if its open, and if its not open then you can designate a shortcut in which it would use to open it for you. 


![image](https://user-images.githubusercontent.com/76603653/158904049-c43c1b41-aee5-494e-8223-e774b90c03e1.png)
